CREATE TABLE auth (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL
);

CREATE TABLE producto (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  detalle VARCHAR(255) NOT NULL,
  valor NUMERIC(10,2) NOT NULL
);
